help: ## Show this help
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)
%:
	@:


run: ## For run application, but before that you must create and fill .env file at deploy directory, by example.env
	cd deploy && docker-compose up

stop: ## For stop application
	cd deploy && docker-compose down && docker rmi deploy_app